# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_google_twingate.connector as __connector
    connector = __connector
else:
    connector = _utilities.lazy_import('pulumi_google_twingate.connector')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "google-twingate",
  "mod": "connector",
  "fqn": "pulumi_google_twingate.connector",
  "classes": {
   "google-twingate:connector:TwingateRegion": "TwingateRegion"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "google-twingate",
  "token": "pulumi:providers:google-twingate",
  "fqn": "pulumi_google_twingate",
  "class": "Provider"
 }
]
"""
)
