// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Activatedio.GoogleTwingate.Connector.Inputs
{

    /// <summary>
    /// Describes the connector instance
    /// </summary>
    public sealed class TwingateConnectorArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access token from Twingate.
        /// </summary>
        [Input("accessToken")]
        public Input<string>? AccessToken { get; set; }

        /// <summary>
        /// Name of the connector.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Refresh token from Twingate.
        /// </summary>
        [Input("refreshToken")]
        public Input<string>? RefreshToken { get; set; }

        /// <summary>
        /// GCP availability zone.
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public TwingateConnectorArgs()
        {
        }
    }
}
