// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export namespace connector {
    /**
     * Describes the connector instance
     */
    export interface TwingateConnectorArgs {
        /**
         * Access token from Twingate.
         */
        accessToken?: pulumi.Input<string>;
        /**
         * Name of the connector.
         */
        name?: pulumi.Input<string>;
        /**
         * Refresh token from Twingate.
         */
        refreshToken?: pulumi.Input<string>;
        /**
         * GCP availability zone.
         */
        zone?: pulumi.Input<string>;
    }
}
